web-development/application/modulos/site/blueprint.py
import os
from flask import current_app, Blueprint, render_template, request, url_for, flash, redirect, session
from datetime import datetime
from flask_mail import Message
from sqlalchemy import desc, and_, or_, asc
from app import mail, executor
from modulos.site.formularios import ContactForm
from database.Model import Configuration, Category, Post, ConfigurationImage, User, Tag, TagPost

siteBP = Blueprint('site', __name__, url_prefix='/', template_folder='templates', static_folder='static')

@siteBP.route('/')
def index():
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()
    tags = Tag.query.join(Post, Tag.posts).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Tag.name)).all()

    news = Post.query.outerjoin(User, User.id == Post.user_id).outerjoin(Category, Category.id == Post.category_id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='news', Post.status=='approved')).order_by(desc(Post.id)).limit(10).all()
    ads = Post.query.filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='ad', Post.status=='approved')).order_by(desc(Post.id)).limit(60).all()
    notices = Post.query.filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='notice', Post.status=='approved')).order_by(desc(Post.id)).limit(6).all()

    return render_template('site/site.html',tags=tags, news=news, ads=ads, notices=notices, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users), 200


@siteBP.route('/noticias')
def noticias():
    return render_post_list_by_type('news', 'Notícias')


@siteBP.route('/noticias/<int:id>')
def noticias_detalhes(id):
    return render_post_detail_by_type('news', 'Notícias', id)


@siteBP.route('/anuncios')
def anuncios():
    return render_post_list_by_type('ad', 'Anúncios')


@siteBP.route('/anuncios/<int:id>')
def anuncios_detalhes(id):
    return render_post_detail_by_type('ad', 'Anúncios', id)


@siteBP.route('/avisos')
def avisos():
    return render_post_list_by_type('notice', 'Avisos')


@siteBP.route('/avisos/<int:id>')
def avisos_detalhes(id):
    return render_post_detail_by_type('notice', 'Avisos', id)


@siteBP.route('/filtro')
def filtro():
    return render_post_list_by_type('filter', 'Filtro')


@siteBP.route('/tag')
def tag():
    return render_post_list_by_type('tag', 'Tag')


@siteBP.route('/contato', methods=['GET','POST'])
def contato():
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()

    form = ContactForm(request.form)
    if form.validate_on_submit():
        try:
            executor.submit(send_email, form)
            flash('Mensagem enviada com sucesso.', 'success')
            return redirect(url_for('site.contato', _anchor='formulario'))
        except:
            flash('Desculpe, ocorreu um problema ao tentar enviar sua mensagem.', 'warning')
        
    return render_template('site/contato.html', form=form, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users), 200


def send_email(form):
    msg = Message('Mensagem de - ' + form.name.data, sender='contato@uniplacdigital.com.br', recipients=['uniplacdigital@gmail.com'])
    msg.html = "<h1>"+ form.assunto.data +"</h1>"
    msg.html += "<ul>"
    msg.html += "<li><b>Nome: </b> "+ form.name.data +"</li>"
    msg.html += "<li><b>Email: </b> "+ form.email.data +"</li>"
    msg.html += "<li><b>Descrição: </b> "+ form.text.data +"</li>"
    msg.html += "</ul>"
    mail.send(msg)
    mail.send(msg)


def render_post_list_by_type(post_type, title):
    titulo = title
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()
    tags = Tag.query.join(Post, Tag.posts).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Tag.name)).all()
    tag = ''
    

    # sidebar avisos
    if post_type == 'notice':
        notices = None
    else:
        notices = Post.query.filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='notice', Post.status=='approved')).order_by(desc(Post.id)).limit(6)

    # filtro/paginação
    page = 1 if (request.args.get('page') == None) else int(request.args.get('page'))
    if post_type == 'filter':
        name = '' if (request.args.get('name') == None) else request.args.get('name')
        genre = '' if (request.args.get('genre') == None) else request.args.get('genre')
        category = '' if (request.args.get('category') == None) else request.args.get('category')
        author  = '' if (request.args.get('author') == None) else request.args.get('author')
        tag = '' if(request.args.get('tag') == None) else request.args.get('tag')
        
        
        # filtro
        filter = (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved'),)
        if category:
            filter = filter + (Post.category_id == category,)
        if name:
            filter = filter + (or_(Post.title.like('%'+name+'%'), Post.description.like('%'+name+'%'), Post.content.like('%'+name+'%')),)
        if genre:
            filter = filter + (Post.genre == genre,)
        if author:
            filter = filter + (Post.user_id == author,)
    elif(post_type == 'tag'): 
        filter = (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved'),)
        tag = '' if (request.args.get('tag') == None) else request.args.get('tag')
        filter = filter + ( Post.tags.any(id=tag),)
    else:
        # fitro
        filter = (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre==post_type, Post.status=='approved'))
    
    # consulta o banco de dados retornando o paginate e os dados
    paginate = Post.query.outerjoin(User, User.id == Post.user_id).outerjoin(Category, Category.id == Post.category_id).filter(*filter).order_by(desc(Post.id)).paginate(page=page, per_page=10, error_out=False)
    posts = paginate.items

    if post_type == 'filter':
        return render_template('site/posts.html', tags=tags, tag=tag, notices=notices, posts=posts, titulo=titulo, name=name, category=category, genre=genre, currentPage=page, paginate=paginate, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users, author=author), 200
    else:
        return render_template('site/posts.html', tags=tags, tag=tag, posts=posts, notices=notices, paginate=paginate, currentPage=page, titulo=titulo, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users), 200


def render_post_detail_by_type(post_type, title, id):
    titulo = title 
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()
    tags = Tag.query.join(Post, Tag.posts).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Tag.name)).all()

    post = None

    # notícia
    if post_type == 'news':
        if session.get('user_role', '') == 'admin' or session.get('user_role', '') == 'editor':
            post = Post.query.filter(and_(Post.id==id, Post.genre=='news')).first()
        else:
            post = Post.query.filter(and_(Post.id==id, Post.genre=='news', Post.status=='approved', Post.entry_date <= current_datetime, Post.departure_date >= current_datetime)).first()

    # anuncio
    if post_type == 'ad':
        ps = Post.query.filter(Post.id==id).first()
        if ps:
            if session.get('user_role', '') == 'user':
                if session.get('user_id', '') == ps.user_id:
                    post = Post.query.filter(and_(Post.id==id, Post.user_id==session.get('user_id', ''), Post.genre=='ad', Post.status!='denied')).first()
                else: 
                    post = Post.query.filter(and_(Post.id==id, Post.genre=='ad', Post.status=='approved', Post.entry_date <= current_datetime, Post.departure_date >= current_datetime)).first()

web-development/application/modulos/site/templates/site/contato.html
{% extends 'base.html' %}

{% from "macros/formFields.html" import render_field, render_file_field, render_hidden_field %}

{% block title %}Contato{% endblock %}

{% block content %}

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content d-md-flex justify-content-between align-items-center">
                <div class="">
                    <h2>Contato</h2>
                </div>
                <div class="page_link">
                    <a href="{{ url_for('site.index') }}" title="Home">Home</a>
                    <strong>Contato</strong>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="sct-contact section_gap">
    <div class="container">
        <div class="d-none d-sm-block mb-5 pb-4 Contact">
            {{ configuration.map|safe }}
            <a id="formulario"></a>
        </div>
        <div class="row">
            <div class="col-12">
                <h2 class="contact-title">Envie uma mensagem</h2>
            </div>
            <div class="col-lg-8 mb-4 mb-lg-0">
                {% from "macros/messageFlash.html" import render_message %}
                {{ render_message() }}
                <form class="form-contact contact_form" action="#formulario" method="post" novalidate>
                    {{ form.csrf_token }}
                    <div class="row">
                        <div class="col-12">
                            {{ render_field(form.assunto, 'required') }}
                        </div>
                        <div class="col-sm-6">
                            {{ render_field(form.name, 'required') }}
                        </div>
                        <div class="col-sm-6">
                            {{ render_field(form.email, 'required email') }}
                        </div>
                        <div class="col-12">
                            {{ render_field(form.text, 'required') }}
                        </div>
                    </div>
                    <div class="form-group mt-lg-3">
                        <button type="submit" class="main_btn">Enviar mensagem</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-4">
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-home"></i></span>
                    <div class="media-body">
                        <h3>{{ configuration.city }}</h3>
                        <p>{{ configuration.address }}</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                    <div class="media-body">
                        <h3>{{ configuration.phone }}</h3>
                        <p>{{ configuration.schedules }}</p>
                    </div>
                </div>
                <div class="media contact-info">
                    <span class="contact-info__icon"><i class="ti-email"></i></span>
                    <div class="media-body">
                        <h3><a href="mailto:uniplac@uniplaclages.br">{{ configuration.email }}</a></h3>
                        <p>Envie-nos a qualquer momento!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}
{% block footer_script %}
<script src="{{ url_for('static', filename='share/js/vanilla-validator.concat.js') }}"></script>
<script>
    var validator = new VanillaValidator({
        messages: {
            required: 'Campo obrigatório',
            email: 'E-mail inválido'
            
        }
    });
  </script>
{% endblock footer_script %}

web-development/application/modulos/site/templates/site/detalhes.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}

<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
    src="https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v5.0&appId=323691997731292&autoLogAppEvents=1"></script>

<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="container">
            <div class="banner_content d-md-flex justify-content-between align-items-center">
                <div class="">
                    <h2> {{ titulo }} </h2>
                </div>
                <div class="page_link">
                    <a href="{{ url_for('site.index') }}" title="Home">Home</a>
                    {% if(titulo == 'Notícias'): %}
                    <a href="{{ url_for('site.noticias') }}" title="{{ titulo }}">{{ titulo }}</a>
                    {% elif(titulo == 'Anuncios'): %}
                    <a href="{{ url_for('site.anuncios') }}" title="{{ titulo }}">{{ titulo }}</a>
                    {% elif(titulo == 'Avisos'): %}
                    <a href="{{ url_for('site.avisos') }}" title="{{ titulo }}">{{ titulo }}</a>
                    {% endif %}
                    <strong>{{ post.title }}</strong>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="blog_area single-post-area section_gap">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 posts-list">

                <div class="single-post">

                    <div class="blog_details">
                        <h1 class="title-post-detail">{{ post.title }}</h1>
                        <ul class="blog-info-link">
                            <li>
                                <div class="post_marker_wrap">
                                    {% if post.genre == 'news' %}
                                    <a href="{{ url_for('site.noticias') }}" title=""
                                        class="post_marker {{post.genre}}">
                                        Notícia
                                    </a>
                                    {% elif post.genre == 'ad' %}
                                    <a href="{{ url_for('site.anuncios') }}" title=""
                                        class="post_marker {{post.genre}}">
                                        Anúncio
                                    </a>
                                    {% elif post.genre == 'notice' %}
                                    <a href="{{ url_for('site.avisos') }}" title="" class="post_marker {{post.genre}}">
                                        Aviso
                                    </a>
                                    {% endif %}
                                </div>
                            </li>
                            <li>
                                <span>
                                    <i class="ti-calendar"></i> {{ post.created_at|format_datetime('%d/%m/%Y') }}
                                </span>
                            </li>
                            <li class="hide-768">
                                <a class="author" href="{{ url_for('site.filtro', author=user.id) }}"
                                    title="Autor {{ user.first_name }} {{ user.last_name }}">
                                    <i class="ti-user"></i> Por {{ user.first_name }} {{ user.last_name }}
                                </a>
                            </li>
                            {% if category.id %}
                            <li>
                                <a href="{{ url_for('site.filtro', category=category.id) }}"
                                    title="Categoria {{ category.name }}">
                                    <i class="ti-tag"></i> {{ category.name }}
                                </a>
                            </li>
                            {% endif %}
                            {% if session.get('user_role', '')  %}
                            {% if post.genre == 'news' and (session.get('user_role', '') == 'admin' or session.get('user_role', '') == 'editor')  %}
                            <li class="hide-768">
                                <a href="{{ url_for('posts.noticias_editar', id=post.id) }}" target="_blank"
                                    title="Editar aviso">
                                    <i class="ti-pencil fa-lg"></i> Editar notícia
                                </a>
                            </li>
                            {% elif post.genre == 'notice' and (session.get('user_role', '') == 'admin' or session.get('user_role', '') == 'author')  %}
                            <li class="hide-768">
                                <a href="{{ url_for('posts.avisos_editar', id=post.id) }}" target="_blank"
                                    title="Editar aviso">
                                    <i class="ti-pencil fa-lg"></i> Editar aviso
                                </a>
                            </li>
                            {% elif post.genre == 'ad'  %}
                            {% if session.get('user_role', '') == 'user' %}
                            {% if post.user_id == session.get('user_id', '') %}
                            <li class="hide-768">
                                <a href="{{ url_for('posts.anuncios_editar', id=post.id) }}" target="_blank"
                                    title="Editar anúncio">
                                    <i class="ti-pencil fa-lg"></i> Editar anúncio
                                </a>
                            </li>
                            {% endif %}
                            {% else %}
                            <li class="hide-768">
                                <a href="{{ url_for('posts.anuncios_editar', id=post.id) }}" target="_blank"
                                    title="Editar anúncio">
                                    <i class="ti-pencil fa-lg"></i> Editar anúncio
                                </a>
                            </li>
                            {% endif %}
                            {% endif  %}
                            {% endif %}
                        </ul>
                        {% if post.image_id != None%}
                        <div class="feature-img">
                            <img class="img-fluid" src="{{request.url_root}}api/media/{{post.image_id}}"
                                alt="{{ post.title }}">
                        </div>
                        {% endif %}
                        <div class="post-content">
                            {{ post.content|safe }}
                        </div>

                    </div>
                    <div class="clear"></div>
                    {% if post.tags %}
                    <hr />
                    <p class="tags">
                        <span class="inline-block"><strong>Tags:</strong></span>
                        {% for tag in post.tags %}
                        <a href="{{ url_for('site.tag', tag=tag.id) }}" class="badge badge-tag">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                {% include 'includes/public/sidebar.html' %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="post-comments">
                    <hr />
                    <div class="fb-comments" data-href="{{request.url}}" data-width="100%" data-numposts="10"></div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

web-development/application/modulos/site/templates/site/site.html
{% extends 'base.html' %}

{% block title %}Início{% endblock %}

{% block content %}

<div>
    <div class="wrapper">
        <div class="slideshow">
            {% for image in configuration.images %}
            <div>
                <img src="{{request.url_root}}api/media/{{image.id}}" alt="Banner Uniplac Digital">
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% if ads %}
<div class="carouse">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row justify-content-between">
                    <div class="col">
                        <h2>Anúncios</h2>
                    </div>
                    <div class="col text-right hide-480">
                        <a href="{{ url_for('site.anuncios') }}" class="btn btn-info btn-sm"
                            title="Ver todos os anúncios">
                            Ver todos os anúncios
                        </a>
                    </div>
                </div>
                <div class="carousel">
                    {% for post in ads %}
                    <div>
                        <div class="card blog__slide text-center">
                            <a href="{{ url_for('site.anuncios_detalhes', id=post.id) }}" class="blog_btn"
                                title="{{ post.title }}">
                                {% if post.image_id == None %}
                                <div class="no-image auto-height">
                                    <div>
                                        <p>{{ post.description }}</p>
                                    </div>
                                </div>
                                {% else %}
                                <div class="blog__slide__img">
                                    <img class="card-img rounded-0"
                                        src="{{request.url_root}}api/media/{{post.image_id}}" alt="{{ post.title }}">
                                </div>
                                {% endif %}
                                <div class="blog__slide__content">
                                    <h3>
                                        <span class="blog_btn">
                                            {{ post.title }}
                                        </span>
                                    </h3>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="row show-480">
                    <div class="col">
                        <a href="{{ url_for('site.anuncios') }}" class="btn btn-info btn-sm btn-block"
                            title="Ver todos os anúnicios">
                            Ver todos os anúncios
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
<section class="blog-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                {% if news %}
                <div class="row">
                    <div class="col">
                        <h2>Últimas Notícias</h2>
                    </div>
                </div>
                {% for post in news %}
                <div class="row">
                    <div class="col-md-12">
                        <div class="single-blog">
                            <div>
                                {% if post.image_id != None %}
                                <a class="thumb" href="{{ url_for('site.noticias_detalhes', id=post.id) }}"
                                    title="{{ post.title }}">
                                    <img class="img-fluid" src="{{request.url_root}}api/media/{{post.image_id}}"
                                        alt="{{ post.title }}">
                                </a>
                                {% endif %}
                                <div class="short_details">
                                    <div class="post_marker_wrap">
                                        <a href="{{ url_for('site.noticias') }}" title=""
                                            class="post_marker {{post.genre}}">
                                            Notícia
                                        </a>
                                    </div>
                                    <a href="{{ url_for('site.noticias_detalhes', id=post.id) }}"
                                        title="{{ post.title }}" class="d-block">
                                        <h3>{{ post.title }}</h3>
                                        <div class="text-wrap">
                                            <p>
                                                {{ post.description }}
                                            </p>
                                        </div>
                                    </a>
                                    <ul class="blog-info-link">
                                        <li>
                                            <span class="date">
                                                <i class="ti-calendar"></i>
                                                {{ post.created_at|format_datetime('%d/%m/%Y') }}
                                            </span>
                                        </li>
                                        <li class="hide-768">
                                            <a class="author" href="{{ url_for('site.filtro', author=post.user.id) }}"
                                                title="Autor {{ post.user.first_name }} {{ post.user.last_name }}">
                                                <i class="ti-user"></i> Por {{ post.user.first_name }}
                                                {{ post.user.last_name }}
                                            </a>
                                        </li>
                                        {% if post.category.id %}
                                        <li>
                                            <a href="{{ url_for('site.filtro', category=post.category.id) }}"
                                                title="Categoria {{ post.category.name }}">
                                                <i class="ti-tag"></i> {{ post.category.name }}
                                            </a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <div class="row">
                    <div class="col-md-12">
                        <a href="{{ url_for('site.noticias') }}" class="btn btn-info btn-block"
                            title="Ver todas as notícias">Ver todas as notícias</a>
                    </div>
                </div>
                {% else %}
                <p class="no-content-found">Nenhuma notícia cadastrada.</p>
                {% endif %}
            </div>
            <div class="col-lg-4">

                {% include 'includes/public/sidebar.html' %}
            </div>
        </div>
    </div>

</section>

{% endblock %}