web-development/application/modulos/site/blueprint.py
import os
from flask import current_app, Blueprint, render_template, request, url_for, flash, redirect, session
from datetime import datetime
from flask_mail import Message
from sqlalchemy import desc, and_, or_, asc
from app import mail, executor
from modulos.site.formularios import ContactForm
from database.Model import Configuration, Category, Post, ConfigurationImage, User, Tag, TagPost

siteBP = Blueprint('site', __name__, url_prefix='/', template_folder='templates', static_folder='static')

@siteBP.route('/')
def index():
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()
    tags = Tag.query.join(Post, Tag.posts).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Tag.name)).all()

    news = Post.query.outerjoin(User, User.id == Post.user_id).outerjoin(Category, Category.id == Post.category_id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='news', Post.status=='approved')).order_by(desc(Post.id)).limit(10).all()
    ads = Post.query.filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='ad', Post.status=='approved')).order_by(desc(Post.id)).limit(60).all()
    notices = Post.query.filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='notice', Post.status=='approved')).order_by(desc(Post.id)).limit(6).all()

    return render_template('site/site.html',tags=tags, news=news, ads=ads, notices=notices, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users), 200


@siteBP.route('/noticias')
def noticias():
    return render_post_list_by_type('news', 'Notícias')


@siteBP.route('/noticias/<int:id>')
def noticias_detalhes(id):
    return render_post_detail_by_type('news', 'Notícias', id)


@siteBP.route('/anuncios')
def anuncios():
    return render_post_list_by_type('ad', 'Anúncios')


@siteBP.route('/anuncios/<int:id>')
def anuncios_detalhes(id):
    return render_post_detail_by_type('ad', 'Anúncios', id)


@siteBP.route('/avisos')
def avisos():
    return render_post_list_by_type('notice', 'Avisos')


@siteBP.route('/avisos/<int:id>')
def avisos_detalhes(id):
    return render_post_detail_by_type('notice', 'Avisos', id)


@siteBP.route('/filtro')
def filtro():
    return render_post_list_by_type('filter', 'Filtro')


@siteBP.route('/tag')
def tag():
    return render_post_list_by_type('tag', 'Tag')


@siteBP.route('/contato', methods=['GET','POST'])
def contato():
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()

    form = ContactForm(request.form)
    if form.validate_on_submit():
        try:
            executor.submit(send_email, form)
            flash('Mensagem enviada com sucesso.', 'success')
            return redirect(url_for('site.contato', _anchor='formulario'))
        except:
            flash('Desculpe, ocorreu um problema ao tentar enviar sua mensagem.', 'warning')
        
    return render_template('site/contato.html', form=form, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users), 200


def send_email(form):
    msg = Message('Mensagem de - ' + form.name.data, sender='contato@uniplacdigital.com.br', recipients=['uniplacdigital@gmail.com'])
    msg.html = "<h1>"+ form.assunto.data +"</h1>"
    msg.html += "<ul>"
    msg.html += "<li><b>Nome: </b> "+ form.name.data +"</li>"
    msg.html += "<li><b>Email: </b> "+ form.email.data +"</li>"
    msg.html += "<li><b>Descrição: </b> "+ form.text.data +"</li>"
    msg.html += "</ul>"
    mail.send(msg)
    mail.send(msg)


def render_post_list_by_type(post_type, title):
    titulo = title
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()
    tags = Tag.query.join(Post, Tag.posts).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Tag.name)).all()
    tag = ''
    

    # sidebar avisos
    if post_type == 'notice':
        notices = None
    else:
        notices = Post.query.filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre=='notice', Post.status=='approved')).order_by(desc(Post.id)).limit(6)

    # filtro/paginação
    page = 1 if (request.args.get('page') == None) else int(request.args.get('page'))
    if post_type == 'filter':
        name = '' if (request.args.get('name') == None) else request.args.get('name')
        genre = '' if (request.args.get('genre') == None) else request.args.get('genre')
        category = '' if (request.args.get('category') == None) else request.args.get('category')
        author  = '' if (request.args.get('author') == None) else request.args.get('author')
        tag = '' if(request.args.get('tag') == None) else request.args.get('tag')
        
        
        # filtro
        filter = (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved'),)
        if category:
            filter = filter + (Post.category_id == category,)
        if name:
            filter = filter + (or_(Post.title.like('%'+name+'%'), Post.description.like('%'+name+'%'), Post.content.like('%'+name+'%')),)
        if genre:
            filter = filter + (Post.genre == genre,)
        if author:
            filter = filter + (Post.user_id == author,)
    elif(post_type == 'tag'): 
        filter = (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved'),)
        tag = '' if (request.args.get('tag') == None) else request.args.get('tag')
        filter = filter + ( Post.tags.any(id=tag),)
    else:
        # fitro
        filter = (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.genre==post_type, Post.status=='approved'))
    
    # consulta o banco de dados retornando o paginate e os dados
    paginate = Post.query.outerjoin(User, User.id == Post.user_id).outerjoin(Category, Category.id == Post.category_id).filter(*filter).order_by(desc(Post.id)).paginate(page=page, per_page=10, error_out=False)
    posts = paginate.items

    if post_type == 'filter':
        return render_template('site/posts.html', tags=tags, tag=tag, notices=notices, posts=posts, titulo=titulo, name=name, category=category, genre=genre, currentPage=page, paginate=paginate, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users, author=author), 200
    else:
        return render_template('site/posts.html', tags=tags, tag=tag, posts=posts, notices=notices, paginate=paginate, currentPage=page, titulo=titulo, configuration=configuration, categories=categories, categories_highlighted=categories_highlighted, users=users), 200


def render_post_detail_by_type(post_type, title, id):
    titulo = title 
    current_datetime = datetime.now()
    configuration = Configuration.query.first()
    categories = Category.query.join(Post, Post.category_id == Category.id).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Category.name)).all()
    categories_highlighted = Category.query.filter((Category.is_highlighted==1)).order_by(asc(Category.name)).all()
    users = User.query.order_by(asc(User.first_name)).all()
    tags = Tag.query.join(Post, Tag.posts).filter(and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime, Post.status=='approved')).order_by(asc(Tag.name)).all()

    post = None

    # notícia
    if post_type == 'news':
        if session.get('user_role', '') == 'admin' or session.get('user_role', '') == 'editor':
            post = Post.query.filter(and_(Post.id==id, Post.genre=='news')).first()
        else:
            post = Post.query.filter(and_(Post.id==id, Post.genre=='news', Post.status=='approved', Post.entry_date <= current_datetime, Post.departure_date >= current_datetime)).first()

    # anuncio
    if post_type == 'ad':
        ps = Post.query.filter(Post.id==id).first()
        if ps:
            if session.get('user_role', '') == 'user':
                if session.get('user_id', '') == ps.user_id:
                    post = Post.query.filter(and_(Post.id==id, Post.user_id==session.get('user_id', ''), Post.genre=='ad', Post.status!='denied')).first()
                else: 
                    post = Post.query.filter(and_(Post.id==id, Post.genre=='ad', Post.status=='approved', Post.entry_date <= current_datetime, Post.departure_date >= current_datetime)).first()

web-development/application/modulos/tags/blueprint.py
from flask import current_app, Blueprint, render_template, request, url_for, redirect, flash, session, jsonify
from sqlalchemy import desc, or_, and_, asc
from app import app
#trocar informações daqui.....
from modulos.tags.formularios import TagForm
from modulos.tags.validations import validateTagToCreate, validateTagToUpdate
from database.Model import db, Post, Tag, User
from database.Model import Configuration

tagBP = Blueprint('tags', __name__, url_prefix='/admin/tags', template_folder='templates', static_folder='static')

@tagBP.route('/')
def index():
    users = User.query.filter(or_(User.role == 'admin', User.role == 'editor')).all()
    configuration = Configuration.query.first()
    titulo = 'Tags'

    # pega os argumentos da string, se existir, senão, seta valores padrão
    page = '1' if (request.args.get('page') == None) else request.args.get('page')
    name = '' if (request.args.get('name') == None) else request.args.get('name')
    order_by = 'id' if (request.args.get('order_by') == None) else request.args.get('order_by')
    order = 'desc' if (request.args.get('order') == None) else request.args.get('order')

    # previne erro ao receber string
    try:
        page = int(page)
    except:
        page = 1

    # previne erro ao recebe string inválida
    if not order_by in ['id', 'name', 'created_at']:
        order_by = 'id'

    # previne erro ao recebe string inválida
    if not order in ['desc', 'asc']:
        order = 'desc'

    # implementa o filtro se necessário
    filter = ()
    if name:
        filter = filter + (Tag.name.like('%'+name+'%'),)

    # gera o order_by
    if order == 'asc':
        query_order = asc(order_by)
    else:
        query_order = desc(order_by)

    # consulta o banco de dados retornando o paginate e os dados
    paginate = Tag.query.filter(*filter).order_by(query_order).paginate(page=page, per_page=10, error_out=False)
    tags = paginate.items

    return render_template('/tags/index.html', users=users, paginate=paginate, tags=tags, currentPage=page, name=name, order_by=order_by, order=order, titulo=titulo, configuration=configuration), 200

@tagBP.route('/cadastrar', methods=['GET','POST'])
def cadastrar():
    configuration = Configuration.query.first()
    form = TagForm(request.form)
    titulo = 'Cadastro'
    if form.validate_on_submit():
        try:
            if validateTagToCreate(form):
                # cria a tag com os dados do formulário
                tag = Tag(
                    form.name.data
                    
                )
                
                # adiciona e commita a tag na base de dados
                db.session.add(tag)
                db.session.commit()

                app.logger.warning(' %s cadastrou a tag %s', session.get('user_name', ''), tag.id)

                # flash message e redireciona pra mesma tela para limpar o objeto request
                flash('Tag cadastrada com sucesso', 'success')
                return redirect(url_for('tags.index'))
        except:
            # remove qualquer vestígio do usuário da sessin e flash message 
            db.session.rollback()
            flash('Erro ao tentar cadastrar a tag', 'danger')
    return render_template('/tags/formulario.html' , titulo=titulo, form=form, configuration=configuration), 200

@tagBP.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar(id):
    configuration = Configuration.query.first()
    # pega a tags pelo id
    tag = Tag.query.filter((Tag.id==id)).first()
    
    # se não existe a tag
    if not tag:
        flash('A tag não exite', 'info')
        return redirect(url_for('tags.index'))
    
    titulo = 'Edição'

    if request.form:
        # formulário preenchido pelo objeto request, caso exista
        form = TagForm(request.form)
    else:
        # formulário vazio
        form = TagForm()

        #preenche formulário com a tag recuperada pelo id
        fillForm(form, tag)

    if form.validate_on_submit():
        try:
            if validateTagToUpdate(form, tag):
                # atualiza a tag recuperada pelo id com os dados do formulário
                tag.name = form.name.data
                

                 # commita os dados na base de dados
                db.session.commit()

                app.logger.warning(' %s editou a tag %s', session.get('user_name', ''), tag.id)

                 # flash message e redireciona pra mesma tela para limpar o objeto request
                flash('Tag editada com sucesso', 'success')
                return redirect(url_for('tags.index', id=id))
        except:
            # remove qualquer vestígio da tag do session e flash message
            db.session.rollback()
            flash('Erro ao tentar editar a tag', 'danger')
    return render_template('/tags/formulario.html' , titulo=titulo, form=form, configuration=configuration), 200

@tagBP.route('/deletar/<int:id>', methods=['GET', 'POST'])
def deletar(id):
    configuration = Configuration.query.first()

    #pega a tag pelo id
    tag = Tag.query.filter((Tag.id==id)).first()

    # se não existe a tag
    if not tag:
        flash('A tag não existe', 'info')
        return redirect(url_for('tags.index'))

    if request.method == 'POST':
        tagId = request.values.get('tagId')
        if tagId:
            # verifica se a tags esta em algum post
            filter = (Post.tags.any(id=tagId),)
            post = Post.query.filter(*filter).all()
            if not post:
            
                try:

                    app.logger.warning(' %s deletou a tag %s', session.get('user_name', ''), tag.id)

                    db.session.delete(tag)
                    db.session.commit()
                    flash('Tag deletada com sucesso', 'success')
                    return redirect(url_for('tags.index'))
                except:
                    db.session.rollback()
                    flash('Erro ao tentar excluir a tag', 'danger')
            else:
                flash('A tag não pode ser deletada pois existem posts relacionadas a ela na base de dados', 'warning')
            
    titulo = 'Deseja realmente excluir a tag ' + tag.name
    return render_template('/tags/deletar.html', titulo=titulo, tagId=id, configuration=configuration), 200

    # popula os campos do formuário
def fillForm(form, tag):
    form.name.data = tag.name


@tagBP.route('/async-check', methods=['POST'])
def asyncCheck():
    if (request.form['name']):
        tag = Tag.query.filter((Tag.name==request.form['name'])).first()
        if tag:
            return jsonify({'message': 'error'})
    return jsonify({'message': 'success'})

web-development/application/templates/includes/admin/navbar.html
{% block navbar %}
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">
            <a class="navbar-brand brand-logo" href="{{ url_for('dashboard.dash') }}" title="Uniplac Digital">
                <img src="{{ url_for('static', filename='admin/images/logo.png') }}" alt="Logo Uniplac" />
            </a>
            <a class="navbar-brand brand-logo-mini" href="{{ url_for('dashboard.dash') }}"  title="Uniplac Digital">
                <img  src="{{ url_for('static', filename='admin/images/logo-mini.png') }}" alt="Logo Uniplac" />
            </a>
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-sort-variant"></span>
            </button>
        </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown" title="{{ session.get('user_name', None) }}">
                    <div class="img-avatar" style="background-image: url({{request.url_root}}api/media/{{ session.get('user_avatar', 0) }})"></div>
                    <span class="nav-profile-name">{{ session.get('user_name', None) }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a class="dropdown-item" href="{{ url_for('site.index') }}" title="Ver Site">
                        <i class="mdi mdi-monitor-multiple text-primary"></i>
                        Ver Site
                    </a>
                    <a class="dropdown-item" href="{{ url_for('posts.meus_posts') }}" title="Minhas Publicações">
                        <i class="mdi mdi-view-list text-primary"></i>
                        Minhas Publicações
                    </a>
                    <a class="dropdown-item" href="{{ url_for('usuarios.editar', id=session.get('user_id', 0)) }}" title="Editar Perfil">
                        <i class="mdi mdi-account text-primary"></i>
                        Editar Perfil
                    </a>
                    <a href="{{ url_for('login.logout') }}" class="dropdown-item" title="Logout">
                        <i class="mdi mdi-logout text-primary"></i>
                        Logout
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
            data-toggle="offcanvas">
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>
{% endblock navbar %}

web-development/application/templates/includes/admin/navigation.html
{% block navigation %}
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('dashboard.dash') }}" title="Dashboard">
                <i class="mdi mdi-home menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        {% if session.get('user_role', '') == 'admin' or session.get('user_role', '') == 'editor'  %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-news" aria-expanded="false" aria-controls="ui-news" title="Notícias">
                <i class="mdi mdi-newspaper menu-icon"></i>
                <span class="menu-title">Notícias</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-news">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.noticias_index') }}" title="Ver Todas">Ver Todas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.noticias_cadastrar') }}" title="Adicionar Nova">Adicionar Nova</a>
                    </li>
                </ul>
            </div>
        </li>
        {% endif %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-ads" aria-expanded="false" aria-controls="ui-ads" title="Anúnicios">
                <i class="mdi mdi-bullhorn menu-icon"></i>
                <span class="menu-title">Anúncios</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-ads">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.anuncios_index') }}" title="Ver Todos">Ver Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.anuncios_cadastrar') }}" title="Adicionar Novo">Adicionar Novo</a>
                    </li>
                </ul>
            </div>
        </li>
        {% if session.get('user_role', '') == 'admin' or session.get('user_role', '') == 'author'  %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-novices" aria-expanded="false" aria-controls="ui-novices" title="Avisos">
                <i class="mdi mdi-sim-alert menu-icon"></i>
                <span class="menu-title">Avisos</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-novices">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.avisos_index') }}" title="Ver Todos">Ver Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.avisos_cadastrar') }}" title="Adicionar Novo">Adicionar Novo</a>
                    </li>
                </ul>
            </div>
        </li>
        {% endif %}
        {% if session.get('user_role', '') == 'admin'  %}
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-user" aria-expanded="false" aria-controls="ui-user" title="Usuários">
                <i class="mdi mdi-account menu-icon"></i>
                <span class="menu-title">Usuários</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-user">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('usuarios.index') }}" title="Ver Todos">Ver Todos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('usuarios.cadastrar') }}" title="Adicionar Novo">Adicionar Novo</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-category" aria-expanded="false" aria-controls="ui-category" title="Categorias">
                <i class="mdi mdi-tag menu-icon"></i>
                <span class="menu-title">Categorias</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-category">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('categorias.index') }}" title="Ver Todas">Ver Todas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('categorias.cadastrar') }}" title="Adicionar Nova">Adicionar Nova</a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#ui-tag" aria-expanded="false"
                    aria-controls="ui-tag">
                    <i class="mdi mdi-tag-multiple menu-icon"></i>
                    <span class="menu-title">Tags</span>
                    <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="ui-tag">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('tags.index') }}" title="Ver todas">Ver todas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('tags.cadastrar') }}" title="Adicionar Nova">Adicionar Novo</a>
                        </li>
                    </ul>
                </div>
            </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('configuracoes.cadastrar') }}" title="Configurações">
                <i class="mdi mdi-settings menu-icon"></i>
                <span class="menu-title">Configurações</span>
            </a>
        </li>
        {% endif  %}
    </ul>
</nav>
{% endblock navigation %}