web-development/application/modulos/posts/blueprint.py
import os
from flask import current_app, Blueprint, render_template, request, url_for, flash, session, redirect
from modulos.posts.formularios import PostForm
from app import app
from sqlalchemy import desc, or_, and_, asc
from database.Model import Configuration, db, Post, Category, User, Tag, TagPost, Category
from datetime import datetime
from flask_mail import Message
from app import mail, executor

postBP = Blueprint('posts', __name__, url_prefix='/admin', template_folder='templates', static_folder='static')

@postBP.route('/noticias')
def noticias_index():
    return render_post_list_by_type('news', 'Notícias')


@postBP.route('/noticias/cadastrar', methods=['GET','POST'])
def noticias_cadastrar():
    return render_post_register_by_type('news', 'Cadastrar Notícia')


@postBP.route('/noticias/editar/<int:id>', methods=['GET','POST'])
def noticias_editar(id):
    return render_post_edit_by_type('news', 'Editar Notícia', id)


@postBP.route('/noticias/deletar/<int:id>', methods=['GET', 'POST'])
def noticias_deletar(id):
    return render_post_delete_by_type('news', 'Deseja realmente excluir a notícia', id)


@postBP.route('/anuncios')
def anuncios_index():
    return render_post_list_by_type('ad', 'Anúncios')


@postBP.route('/anuncios/cadastrar', methods=['GET','POST'])
def anuncios_cadastrar():
    return render_post_register_by_type('ad', 'Cadastrar Anúncio')


@postBP.route('/anuncios/editar/<int:id>', methods=['GET','POST'])
def anuncios_editar(id):
    return render_post_edit_by_type('ad', 'Editar Anúncio', id)


@postBP.route('/anuncios/deletar/<int:id>', methods=['GET', 'POST'])
def anuncios_deletar(id):
    return render_post_delete_by_type('ad', 'Deseja realmente excluir o anúncio', id)


@postBP.route('/avisos')
def avisos_index():
    return render_post_list_by_type('notice', 'Avisos')


@postBP.route('/avisos/cadastrar', methods=['GET','POST'])
def avisos_cadastrar():
    return render_post_register_by_type('notice', 'Cadastrar Aviso')


@postBP.route('/avisos/editar/<int:id>', methods=['GET','POST'])
def avisos_editar(id):
    return render_post_edit_by_type('notice', 'Editar Aviso', id)


@postBP.route('/avisos/deletar/<int:id>', methods=['GET', 'POST'])
def avisos_deletar(id):
    return render_post_delete_by_type('notice', 'Deseja realmente excluir o aviso', id)


@postBP.route('/meus-posts')
def meus_posts():
    return render_post_list_by_type('meus-posts', 'Minhas Publicações')


# popula os campos do formuário
def fillForm(form, post, genre):
    form.title.data = post.title 
    form.description.data = post.description 
    form.content.data = post.content 
    form.genre = genre
    form.status.data = post.status
    form.entry_date.data = post.entry_date
    form.departure_date.data = post.departure_date
    form.image_id.data = None
    if (post.image_id != ''):
        form.image_id.data = post.image_id 
    form.user_id = session.get('user_id', '')
    form.category_id.data = str(post.category_id)


# remove as validações de data
def clearDateValidatons(post, form):
    if post.entry_date == form.entry_date.data:
        form.entry_date.validators = []
        field = form.entry_date
        def nullValidate(self, field):
            return True
        form.entry_date.validate = nullValidate

    if post.departure_date == form.departure_date.data:
        form.departure_date.validators = []
        field = form.departure_date
        def nullValidate(self, field):
            return True
        form.departure_date.validate = nullValidate


# LISTAGEM DE POSTS
def render_post_list_by_type(post_type, title):
    configuration = Configuration.query.first()
    titulo = title
    current_datetime = datetime.now()
    categories = Category.query.join(Post, Post.category_id == Category.id).order_by(asc(Category.name)).all()
    users = None
    if post_type == 'news':
        users = User.query.order_by(asc(User.first_name)).filter(or_(User.role == 'admin', User.role == 'editor')).all()
    elif post_type == 'notice':
        users = User.query.order_by(asc(User.first_name)).filter(or_(User.role == 'admin', User.role == 'author')).all()
    elif post_type == 'ad':
        users = User.query.order_by(asc(User.first_name)).filter().all()

    # pega os argumentos da string, se existir, senão, seta valores padrão
    page = '1' if (request.args.get('page') == None) else request.args.get('page')
    name = '' if (request.args.get('name') == None) else request.args.get('name')
    category = '' if (request.args.get('category') == None) else request.args.get('category')
    status = '' if (request.args.get('status') == None) else request.args.get('status')
    order_by = 'id' if (request.args.get('order_by') == None) else request.args.get('order_by')
    order = 'desc' if (request.args.get('order') == None) else request.args.get('order')
    publication = '' if (request.args.get('publication') == None) else request.args.get('publication')
    author = ''
    if post_type != 'meus-posts':
        author = '' if (request.args.get('author') == None) else request.args.get('author')

    # previne erro ao receber string
    try:
        page = int(page)
    except:
        page = 1

    # previne erro ao recebe string inválida
    if not order_by in ['id', 'title', 'created_at']:
        order_by = 'id'

    # previne erro ao recebe string inválida
    if not order in ['desc', 'asc']:
        order = 'desc'

    # implementa o filtro se necessário
    if post_type != 'meus-posts':
        filter = (Post.genre == post_type, )
    else:
        filter = (Post.user_id == session.get('user_id', ''), )
    if category:
        filter = filter + (Post.category_id == category,)
    if name:
        filter = filter + (or_(Post.title.like('%'+name+'%'), Post.description.like('%'+name+'%'), Post.content.like('%'+name+'%')),)
    if status:
        filter = filter + (Post.status == status,)
    if publication == 'current':
        filter = filter + (and_(Post.entry_date <= current_datetime, Post.departure_date >= current_datetime),)
    elif publication == 'expired':
        filter = filter + (and_(Post.departure_date < current_datetime),)
    elif publication == 'scheduled':
        filter = filter + (and_(Post.entry_date > current_datetime),)

    if post_type != 'meus-posts':
        if author:
            filter = filter + (Post.user_id == author, )
    
    if post_type == 'ad':
        if session.get('user_role', '') == 'user':
            filter = filter + (Post.user_id == session.get('user_id', ''), )

    # gera o order_by
    if order == 'asc':
        query_order = asc(order_by)
    else:
        query_order = desc(order_by)

    # consulta o banco de dados retornando o paginate e os dados
    paginate = Post.query.filter(*filter).order_by(query_order).paginate(page=page, per_page=10, error_out=False)
    posts = paginate.items

    return render_template('/posts/index.html', current_datetime=current_datetime, categories=categories, paginate=paginate, posts=posts, currentPage=page, name=name, category=category, status=status, order_by=order_by, order=order, titulo=titulo, configuration=configuration, publication=publication, users=users), 200


# CADASTRO DE POSTS
def render_post_register_by_type(post_type, title):
    configuration = Configuration.query.first()
    form = PostForm(request.form)
    titulo = title

    if post_type == 'ad':
        if session.get('user_role', '') == 'user':
            form.status.validators = []

    form.category_id.choices = [('', 'Selecione')]
    try:
        categories = Category.query.all()
        for category in categories:
            form.category_id.choices.append((str(category.id), category.name))
    except:
        pass

    if form.validate_on_submit():
        try:
            form.user_id = session.get('user_id', '')

            # cria o post com os dados do formulário
            post = Post(
                form.title.data,
                form.description.data,
                form.content.data,
                post_type,
                '',
                form.entry_date.data,
                form.departure_date.data,
                None,
                form.user_id,
                None
            )

            if post_type == 'ad':
                if session.get('user_role', '') == 'user':
                    post.status = 'pending'
                else:
                    post.status = form.status.data
            else:
                post.status = form.status.data

            if form.image_id.data != '':
                post.image_id = form.image_id.data

            #adiciona a tag no banco
            tags = form.tag.data
            array_tags = tags.split(',')
            for t in array_tags:
                if t.strip() == '':
                    continue
                tag = Tag.query.filter((Tag.name==t)).first()
                if tag:
                    post.tags.append(tag)
        
                else:
                    tag = Tag(t)
                    post.tags.append(tag)

            if form.category_id.data != '':
                post.category_id = form.category_id.data

            db.session.add(post)
            db.session.commit()

            if post_type == 'news':
                executor.submit(send_post_email, 'Novo cadastro de notícia', 'O usuário ' + session.get('user_name', '') + ' cadastrou uma nova notícia.')
                app.logger.warning(' %s cadastrou a notícia %s', session.get('user_name', ''), post.title)
                flash('Notícia cadastrada com sucesso', 'success')
                return redirect(url_for('posts.noticias_index'))
            elif post_type == 'notice':
                executor.submit(send_post_email, 'Novo cadastro de aviso', 'O usuário ' + session.get('user_name', '') + ' cadastrou um novo aviso.')
                app.logger.warning(' %s cadastrou o aviso %s', session.get('user_name', ''), post.title)

web-development/application/modulos/posts/templates/posts/deletar.html
{% extends 'base-admin.html' %}

{% block title %}
{{ pergunta }}
{% endblock title %}

{% block content %}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <ul class="ul-breadcrumb">
            <li>
                <a href="{{ url_for('dashboard.dash') }}" title="Dashboard">Dashboard</a>
            </li>
            {% if titulo == 'Notícias' %}
                <li>
                    <a href="{{ url_for('posts.noticias_index') }}" title="Notícias">Notícias</a>
                </li>
            {% endif %}
            {% if titulo == 'Anúncios' %}
                <li>
                    <a href="{{ url_for('posts.anuncios_index') }}" title="Anúncios">Anúncios</a>
                </li>
            {% endif %}
            {% if titulo == 'Avisos' %}
                <li>
                    <a href="{{ url_for('posts.avisos_index') }}" title="Avisos">Avisos</a>
                </li>
            {% endif %}
            <li>
                <b>Excluir</b>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h4>{{ pergunta }}</h4>
        <hr>
        {# Diferenciando pelo tipo de post #}
        {% if(post_type == 'news'): %}
        <form action="{{ url_for('posts.noticias_deletar', id=postId) }}" method="POST">
            <button type="submit" class="btn btn-danger">Excluir</button>
            <input type="hidden" name="postId" value="{{ postId }}">
            <a href="{{ url_for('posts.noticias_index') }}" class="btn btn-secondary" title="Cancelar">Cancelar</a>
        </form>
        {% elif(post_type == 'ad'): %}
        <form action="{{ url_for('posts.anuncios_deletar', id=postId) }}" method="POST">
            <button type="submit" class="btn btn-danger">Excluir</button>
            <input type="hidden" name="postId" value="{{ postId }}">
            <a href="{{ url_for('posts.anuncios_index') }}" class="btn btn-secondary" title="Cancelar">Cancelar</a>
        </form>
        {% elif(post_type == 'notice'): %}
        <form action="{{ url_for('posts.avisos_deletar', id=postId) }}" method="POST">
            <button type="submit" class="btn btn-danger">Excluir</button>
            <input type="hidden" name="postId" value="{{ postId }}">
            <a href="{{ url_for('posts.avisos_index') }}" class="btn btn-secondary" title="Cancelar">Cancelar</a>
        </form>
        {% endif %}
    </div>
</div>
{% endblock content %}