web-development/application/modulos/tags/__init__.py
from modulos.tags.blueprint import tagBP

web-development/application/modulos/tags/blueprint.py
from flask import current_app, Blueprint, render_template, request, url_for, redirect, flash, session, jsonify
from sqlalchemy import desc, or_, and_, asc
from app import app
#trocar informações daqui.....
from modulos.tags.formularios import TagForm
from modulos.tags.validations import validateTagToCreate, validateTagToUpdate
from database.Model import db, Post, Tag, User
from database.Model import Configuration

tagBP = Blueprint('tags', __name__, url_prefix='/admin/tags', template_folder='templates', static_folder='static')

@tagBP.route('/')
def index():
    users = User.query.filter(or_(User.role == 'admin', User.role == 'editor')).all()
    configuration = Configuration.query.first()
    titulo = 'Tags'

    # pega os argumentos da string, se existir, senão, seta valores padrão
    page = '1' if (request.args.get('page') == None) else request.args.get('page')
    name = '' if (request.args.get('name') == None) else request.args.get('name')
    order_by = 'id' if (request.args.get('order_by') == None) else request.args.get('order_by')
    order = 'desc' if (request.args.get('order') == None) else request.args.get('order')

    # previne erro ao receber string
    try:
        page = int(page)
    except:
        page = 1

    # previne erro ao recebe string inválida
    if not order_by in ['id', 'name', 'created_at']:
        order_by = 'id'

    # previne erro ao recebe string inválida
    if not order in ['desc', 'asc']:
        order = 'desc'

    # implementa o filtro se necessário
    filter = ()
    if name:
        filter = filter + (Tag.name.like('%'+name+'%'),)

    # gera o order_by
    if order == 'asc':
        query_order = asc(order_by)
    else:
        query_order = desc(order_by)

    # consulta o banco de dados retornando o paginate e os dados
    paginate = Tag.query.filter(*filter).order_by(query_order).paginate(page=page, per_page=10, error_out=False)
    tags = paginate.items

    return render_template('/tags/index.html', users=users, paginate=paginate, tags=tags, currentPage=page, name=name, order_by=order_by, order=order, titulo=titulo, configuration=configuration), 200

@tagBP.route('/cadastrar', methods=['GET','POST'])
def cadastrar():
    configuration = Configuration.query.first()
    form = TagForm(request.form)
    titulo = 'Cadastro'
    if form.validate_on_submit():
        try:
            if validateTagToCreate(form):
                # cria a tag com os dados do formulário
                tag = Tag(
                    form.name.data
                    
                )
                
                # adiciona e commita a tag na base de dados
                db.session.add(tag)
                db.session.commit()

                app.logger.warning(' %s cadastrou a tag %s', session.get('user_name', ''), tag.id)

                # flash message e redireciona pra mesma tela para limpar o objeto request
                flash('Tag cadastrada com sucesso', 'success')
                return redirect(url_for('tags.index'))
        except:
            # remove qualquer vestígio do usuário da sessin e flash message 
            db.session.rollback()
            flash('Erro ao tentar cadastrar a tag', 'danger')
    return render_template('/tags/formulario.html' , titulo=titulo, form=form, configuration=configuration), 200

@tagBP.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar(id):
    configuration = Configuration.query.first()
    # pega a tags pelo id
    tag = Tag.query.filter((Tag.id==id)).first()
    
    # se não existe a tag
    if not tag:
        flash('A tag não exite', 'info')
        return redirect(url_for('tags.index'))
    
    titulo = 'Edição'

    if request.form:
        # formulário preenchido pelo objeto request, caso exista
        form = TagForm(request.form)
    else:
        # formulário vazio
        form = TagForm()

        #preenche formulário com a tag recuperada pelo id
        fillForm(form, tag)

    if form.validate_on_submit():
        try:
            if validateTagToUpdate(form, tag):
                # atualiza a tag recuperada pelo id com os dados do formulário
                tag.name = form.name.data
                

                 # commita os dados na base de dados
                db.session.commit()

                app.logger.warning(' %s editou a tag %s', session.get('user_name', ''), tag.id)

                 # flash message e redireciona pra mesma tela para limpar o objeto request
                flash('Tag editada com sucesso', 'success')
                return redirect(url_for('tags.index', id=id))
        except:
            # remove qualquer vestígio da tag do session e flash message
            db.session.rollback()
            flash('Erro ao tentar editar a tag', 'danger')
    return render_template('/tags/formulario.html' , titulo=titulo, form=form, configuration=configuration), 200

@tagBP.route('/deletar/<int:id>', methods=['GET', 'POST'])
def deletar(id):
    configuration = Configuration.query.first()

    #pega a tag pelo id
    tag = Tag.query.filter((Tag.id==id)).first()

    # se não existe a tag
    if not tag:
        flash('A tag não existe', 'info')
        return redirect(url_for('tags.index'))

    if request.method == 'POST':
        tagId = request.values.get('tagId')
        if tagId:
            # verifica se a tags esta em algum post
            filter = (Post.tags.any(id=tagId),)
            post = Post.query.filter(*filter).all()
            if not post:
            
                try:

                    app.logger.warning(' %s deletou a tag %s', session.get('user_name', ''), tag.id)

                    db.session.delete(tag)
                    db.session.commit()
                    flash('Tag deletada com sucesso', 'success')
                    return redirect(url_for('tags.index'))
                except:
                    db.session.rollback()
                    flash('Erro ao tentar excluir a tag', 'danger')
            else:
                flash('A tag não pode ser deletada pois existem posts relacionadas a ela na base de dados', 'warning')
            
    titulo = 'Deseja realmente excluir a tag ' + tag.name
    return render_template('/tags/deletar.html', titulo=titulo, tagId=id, configuration=configuration), 200

    # popula os campos do formuário
def fillForm(form, tag):
    form.name.data = tag.name


@tagBP.route('/async-check', methods=['POST'])
def asyncCheck():
    if (request.form['name']):
        tag = Tag.query.filter((Tag.name==request.form['name'])).first()
        if tag:
            return jsonify({'message': 'error'})
    return jsonify({'message': 'success'})

web-development/application/modulos/tags/templates/tags/deletar.html
{% extends 'base-admin.html' %}

{% block title%}
{{ titulo }}
{% endblock title%}

{% block content %}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <ul class="ul-breadcrumb">
            <li>
                <a href="{{ url_for('dashboard.dash') }}" title="Dashboard">Dashboard</a>
            </li>
            <li>
                <a href="{{ url_for('tags.index') }}" title="Tags">Tags</a>
            </li>
            <li>
                <b>Excluir</b>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <h4>{{ titulo }}</h4>
        <hr>
        <form action="{{ url_for('tags.deletar', id=tagId) }}" method="POST">
            <button type="submit" class="btn btn-danger">Excluir</button>
            <input type="hidden" name="tagId" value="{{ tagId }}">
            <a href="{{ url_for('tags.index') }}" class="btn btn-secondary" title="Cancelar">Cancelar</a>
        </form>
    </div>
</div>
{% endblock content %}

web-development/application/modulos/tags/templates/tags/formulario.html
{% extends 'base-admin.html' %}

{% from "macros/formFields.html" import render_field, render_checkbox_field %}

{% block title%}
{{ titulo }} de Tags
{% endblock title%}

{% block content %}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <ul class="ul-breadcrumb">
            <li>
                <a href="{{ url_for('dashboard.dash') }}" title="Dashboard">Dashboard</a>
            </li>
            <li>
                <a href="{{ url_for('tags.index') }}" title="Tags">Tags</a>
            </li>
            <li>
                <b>{{ titulo }} de Tags</b>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ titulo }} de Tags</h4>
                <form class="forms-sample" method="POST" novalidate>
                    {{ form.csrf_token }}
                    {{ render_field(form.name, 'required async', '45') }}
                    <input type="hidden" id="old-tag" value="{{ form.name.data }}" />
                    <br />
                    <button type="submit" class="btn btn-primary mr-2">Enviar</button>
                    <button type="button" class="btn btn-light"
                        onClick="history.go(-1); return false;">Cancelar</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

{% block footer_script %}
<script>
    var validator = new VanillaValidator({
        messages: {
            required: 'Campo obrigatório'
        },
        asyncValidates: {
            'tag-input': {
                message: 'verificando disponibilidade do nome...',
                fn: function (field, message, container) {
                    var self = this;
                    this.asyncValidationStart(field, 'verificando disponibilidade do nome...', container);
                    if ($('#old-tag') && $('#old-tag').val() === field.value && field.value !== '') {
                        self.asyncValidationFinish(field, '', container, true);
                    } else {
                        if (field.value === '') {
                            self.asyncValidationFinish(field, 'Campo obrigatório', container, false);
                        } else {
                            $.ajax({
                                method: 'POST',
                                url: '/admin/tags/async-check',
                                data: { name: field.value }
                            }).done(function (data) {
                                if (data && data.message && data.message === 'success') {
                                    self.asyncValidationFinish(field, '', container, true);
                                } else {
                                    self.asyncValidationFinish(field, 'Uma Tag com este nome já existe na base de dados', container, false);
                                }
                             });
                        }
                    }
                }
            }
        }
    });
</script>
{% endblock footer_script %}

web-development/application/modulos/tags/templates/tags/index.html
{% extends 'base-admin.html' %}

{% block title%}
{{ titulo }}
{% endblock title%}

{% block content %}

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <ul class="ul-breadcrumb">
            <li>
                <a href="{{ url_for('dashboard.dash') }}" title="Dashboard">Dashboard</a>
            </li>
            <li>
                <b>{{ titulo }}</b>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <!--Lista de Tags-->
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ titulo }}</h4>

                <form class="formm-search" action="{{ url_for('tags.index') }}" method="GET" novalidate>
                    <div class="row show-768">
                        <div class="col-md-12">
                            <p class="btn filtro">
                                Filtro:
                                <span class="btn-search show-768 open-mbl-search-form"><i class="mdi mdi-magnify"></i></span>
                            </p>
                        </div>
                    </div>
                    <div class="row mbl-hided-row">
                        <div class="col-md-1 hide-768">
                            <p class="btn">
                                Filtro:
                            </p>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <input name="name" type="text" class="form-control form-control-sm"
                                    placeholder="Palavra chave" value="{{name}}">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <input type="hidden" name="order" value="{{ order }}" />
                            <input type="hidden" name="order_by" value="{{ order_by }}" />
                            <button type="submit" class="btn btn-primary btn-sm btn-block">Filtrar</button>
                        </div>
                    </div>
                </form>

                <div class="table-responsive">
                    {% if tags|length > 0 %}
                    {% if order == 'asc' %}
                    {% set _order = 'desc' %}
                    {% else %}
                    {% set _order = 'asc' %}
                    {% endif %}
                    <table class="table table-striped table-mbl">
                        <thead>
                            <tr>
                                <th>
                                    <a href="{{ url_for('tags.index', page=currentPage, name=name, order_by='id', order=_order) }}"
                                        class="{{ 'active' if order_by=='id' else '' }}" title="Ordenar por ID">ID</a>
                                </th>
                                <th>
                                    <a href="{{ url_for('tags.index', page=currentPage, name=name, order_by='name', order=_order) }}"
                                        class="{{ 'active' if order_by=='name' else '' }}" title="Ordenar por Nome">Nome</a>
                                </th>
                                <th>
                                    <a href="{{ url_for('tags.index', page=currentPage, name=name, order_by='created_at', order=_order) }}"
                                        class="{{ 'active' if order_by=='created_at' else '' }}"
                                        title="Ordenar por Data">Data</a>
                                </th>
                                <th>Editar/Deletar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tag in tags %}
                            <tr>
                                <td>{{ tag.id }}</td>
                                <td>{{ tag.name }}</td>
                                <td>{{ tag.created_at|format_datetime('%d/%m/%Y') }}</td>
                                <td>
                                    <a href="{{ url_for('tags.editar', id=tag.id) }}">
                                        <i class="mdi mdi-border-color edit"></i>
                                    </a>
                                    <a href="{{ url_for('tags.deletar', id=tag.id) }}">
                                        <i class="mdi mdi-delete-forever delete"></i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="table-pagination">
                        <div class="btn-group" role="group" aria-label="Basic example">
                            {% if paginate.next_num != None or paginate.prev_num != None %}
                            {% for page in paginate.iter_pages(left_edge=2, left_current=2, right_current=3, right_edge=2) %}
                            {% if page == None %}
                            <button type="button" class="btn">...</button>
                            {% else %}
                            <a href="{{ url_for('tags.index', page=page, name=name, order_by=order_by, order=order) }}"
                                class="btn btn-primary {{ 'active' if currentPage == page else '' }}"
                                title="Página {{page}}">{{ page }}</a>
                            {% endif %}
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    {% else %}
                    <p class="no-content-found">Nenhuma Tag encontrada.</p>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock content%}